#!/usr/bin/env python3
"""Assembles EVIDENCE.md from the raw JSON files collected by collect_evidence.sh.
Every embedded block is a real, unedited response from your running instance --
this script only formats and highlights, it never fabricates content."""
import json
from pathlib import Path

EV = Path("./evidence")
OUT = Path("EVIDENCE.md")


def load(name):
    p = EV / name
    if not p.exists():
        return None
    text = p.read_text()
    try:
        return json.loads(text)
    except Exception:
        return text  # e.g. redirect_headers.txt, or an empty/error body


def block(data, lang="json"):
    if data is None:
        return "_(missing -- re-run collect_evidence.sh, or check BASE_URL/API_KEY)_\n"
    if isinstance(data, str):
        text = data
    else:
        text = json.dumps(data, indent=2)
    return "```" + lang + "\n" + text + "\n```\n"


# Matches the exact order of AuditEventType.cs -- GET /pipeline/{id}/audit
# returns the raw enum as an int (no string converter registered), while
# GET /pipeline/{id} calls .ToString() on the same enum. This maps either
# representation back to its name so the rest of the script doesn't care.
AUDIT_EVENT_TYPE_NAMES = [
    "PipelineStarted", "StageEntered", "StageCompleted", "StageFailed",
    "RetryScheduled", "RetryAttempt", "RolledBack", "ApprovalPending",
    "ApprovalDecision", "ApprovalTimeout", "SafeStop", "PipelineCompleted",
    "Cancelled",
]


def event_type_name(raw):
    if isinstance(raw, bool):
        return str(raw)
    if isinstance(raw, int):
        if 0 <= raw < len(AUDIT_EVENT_TYPE_NAMES):
            return AUDIT_EVENT_TYPE_NAMES[raw]
        return "Unknown(" + str(raw) + ")"
    return str(raw)


def event_types(audit):
    if not isinstance(audit, dict) or "entries" not in audit:
        return []
    result = []
    for e in audit["entries"]:
        raw = e.get("eventType", e.get("EventType", "?"))
        result.append(event_type_name(raw))
    return result


lines = []
lines.append("# Evidence -- Agentic SDLC Orchestration Engine")
lines.append("")
lines.append(
    "Every block below is an unedited response captured from a running instance via "
    "collect_evidence.sh, not hand-written. Generated by build_evidence_doc.py."
)
lines.append("")

# ---------------- Part 1: URL shortener ----------------
lines.append("## 1. URL Shortener -- core product")
lines.append("")
shorten = load("shorten.json")
lines.append("**POST /shorten**")
lines.append(block(shorten))
lines.append(
    "**GET /{code} -- raw headers via curl -I** "
    "(confirms a real 302, not a client-followed redirect)"
)
lines.append(block(load("redirect_headers.txt"), "text"))
lines.append("**GET /{code}/analytics**")
lines.append(block(load("analytics.json")))
health = load("health.json")
if health is not None:
    lines.append("**GET /health**")
    lines.append(block(health))

# ---------------- Part 2: Three scenarios ----------------
lines.append("")
lines.append("## 2. Three Required Scenarios")
lines.append("")

scenario_tags = ["greenfield", "brownfield", "ambiguous"]
scenario_labels = {
    "greenfield": "Greenfield -- core shorten/redirect API built from scratch",
    "brownfield": "Brownfield -- analytics added to the existing service",
    "ambiguous": "Ambiguous -- reliability features; spec gap resolved by the Requirements stage",
}

for tag in scenario_tags:
    label = scenario_labels[tag]
    audit = load(tag + "_audit.json")
    metrics = load(tag + "_metrics.json")
    lines.append("### " + label)
    lines.append("")
    if isinstance(audit, dict):
        types = event_types(audit)
        unique_types = ", ".join(sorted(set(types)))
        chain = audit.get("chainIntegrity")
        lines.append("- Chain integrity: **" + str(chain) + "**")
        lines.append("- " + str(len(types)) + " audit entries -- event types present: " + unique_types)
        lines.append("")
    lines.append("**Audit log**")
    lines.append(block(audit))
    lines.append("**Metrics**")
    lines.append(block(metrics))

# ---------------- Part 3: Retry -> rollback ----------------
lines.append("")
lines.append("## 3. Retry -> Rollback Proof")
lines.append("")
rr_audit = load("retry_rollback_audit.json")
if isinstance(rr_audit, dict):
    types = event_types(rr_audit)
    has_rollback = "RolledBack" in types
    sequence = " -> ".join(types)
    lines.append("- Contains RolledBack event: **" + str(has_rollback) + "**")
    lines.append("- Full event sequence: " + sequence)
    lines.append("")
lines.append("**Audit log for the injected-failure run**")
lines.append(block(rr_audit))

# ---------------- Part 4: Rejection ----------------
lines.append("")
lines.append("## 4. Human Rejection Path")
lines.append("")
rej_audit = load("rejection_audit.json")
if isinstance(rej_audit, dict):
    types = event_types(rej_audit)
    has_safestop = "SafeStop" in types
    lines.append("- Contains SafeStop event: **" + str(has_safestop) + "**")
    lines.append("")
lines.append(block(rej_audit))

# ---------------- Part 5: Cancellation ----------------
lines.append("")
lines.append("## 5. Cancellation")
lines.append("")
cancel_status = load("cancel_status.json")
cancel_audit = load("cancel_audit.json")
if isinstance(cancel_status, dict):
    lines.append("- Final status: **" + str(cancel_status.get("status")) + "**")
if isinstance(cancel_audit, dict):
    types = event_types(cancel_audit)
    has_cancelled = "Cancelled" in types
    chain = cancel_audit.get("chainIntegrity")
    lines.append("- Chain integrity: **" + str(chain) + "**")
    lines.append("- Contains Cancelled event: **" + str(has_cancelled) + "**")
lines.append("")
lines.append("**Status**")
lines.append(block(cancel_status))
lines.append("**Audit log**")
lines.append(block(cancel_audit))

# ---------------- Part 6: Aggregate ----------------
lines.append("")
lines.append("## 6. Aggregate Metrics Across All Runs")
lines.append("")
lines.append(block(load("aggregate_metrics.json")))
lines.append("**All recorded runs**")
lines.append(block(load("list_runs.json")))

OUT.write_text("\n".join(lines))
print("Wrote " + str(OUT.resolve()) + " (" + str(OUT.stat().st_size) + " bytes)")
